### ISSUE TITLE
[Feature Request] Show neighbors

### ISSUE THREAD

**Issue by DrCoolzic** [dmulcahey/zha-network-card#25]
It would be nice to show the ieee or nwk id of the device neighbors. 
For example a comma separated lis for children, and a comma separated list for parents.

**Comment by deviantintegral** [comment]
I was able to get this to work with:

```yaml
          - name: Neighbours
            attr: neighbors
            modify: >-
              x.map((n, idx) => { let s = ""; if (idx > 0) s = "<br />"; s = s+
              n.relationship + " " + n.ieee; return s; })
```

<img width="2259" alt="Screen Shot 2021-05-05 at 8 39 30 AM" src="https://user-images.githubusercontent.com/255023/117142187-6ad82700-ad7d-11eb-964f-bc9fa23dd1eb.png">

For a minute, I thought the undocumented `attr_as_list` option would do it, but it ends up exploding each device into multiple rows, messing up all of the attributes that are not lists.
