### ISSUE TITLE
card isn't rendering correctly

### ISSUE THREAD

**Issue by finity69x2** [dmulcahey/zha-network-card#3]
Just added this card and it isn't rendering correctly.

here is the code for the view:

```
title: Zigbee
cards:
  - type: 'custom:zha-network-card'
    title: Zigbee Network Information
    columns:
      - prop: name
        name: Name
      - attr: manufacturer
        name: Manufacturer
      - attr: model
        name: Model
      - attr: ieee
        name: IEEE
      - prop: nwk
        name: NWK
      - attr: rssi
        name: RSSI
      - attr: lqi
        name: LQI
      - attr: last_seen
        name: Last Seen
      - attr: power_source
        name: Power Source
      - attr: quirk_class
        name: Quirk
```

here is the screen shot:

![ex](https://user-images.githubusercontent.com/32221243/62056049-d37a9300-b1ea-11e9-84cb-8346fb19c2a2.gif)

As you can see the last four columns are completely cut off

As far as I know I've got nothing in my lovelace code that would cause that. none of my other views/cards show that behavior.

running non-hassio HA v96.3
