### ISSUE TITLE
custom zha-network-card stopped working after a January 2023 update

### ISSUE THREAD

**Issue by mrneutron42** [dmulcahey/zha-network-card#31]
Several HA updates have been applied in the first 11 days of 2023.
I'm currently up to:
Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest
 
This morning, the zha-network-card was working.
Then, I rebooted HA and suddenly the custom zha-network-card stopped working.
Has this happened to anyone else?
![zha-network-card stopped working Jan 2023](https://user-images.githubusercontent.com/70338169/211919376-4067530d-ab19-4e9a-8e42-bd488cf84eb8.JPG)
I'm not sure how to fix it, or if it can be fixed.

I have been checking to be sure all the aspects of configuration are correct.
It's been several years since I installed it, and since then, the HA interface has been changed and re-arranged. 
I think the installation how-to is out of date.
Can someone help me figure out what the correct configuration is?
There was an HA message that complained about having the "resources:" lines in the main configuration, and suggested it should be moved to the Configuration window, so I just did that, but it didn't help.
Does this look right?

![zha-network-card Lovelace configuration](https://user-images.githubusercontent.com/70338169/211920382-a94b98df-2824-458c-860b-d40e501caa9b.JPG)

![zha-network-card home view configuration settings](https://user-images.githubusercontent.com/70338169/211922053-4b507c8e-4562-435e-b11c-0c58daf32a15.JPG)

```
clickable: true
panel: true
columns:
  - name: Name
    prop: name
  - attr: available
    id: available
    modify: x || "false"
    name: Online
  - attr: manufacturer
    name: Manufacturer
  - attr: model
    name: Model
  - attr: ieee
    name: IEEE
  - name: NWK
    prop: nwk
  - attr: rssi
    name: RSSI
  - attr: lqi
    name: LQI
  - attr: last_seen
    name: Last Seen
  - attr: power_source
    name: Power Source
  - attr: quirk_class
    name: Quirk
sort_by: available
type: custom:zha-network-card
```

**Comment by mrneutron42** [comment]
I got it working again!
The zha-network-card.js file is in the /config/www/ directory
I removed the "resources:" lines to the UI Configuration window, and made sure that the Resources Editor had an entry pointing to /local/zha-network-card.js

![zha-network-card Manage Resources](https://user-images.githubusercontent.com/70338169/211946392-253be1e3-e2a3-4398-a3c7-986382cc47e7.JPG)

This is the resulting card configuration via the Raw Configuration Editor:

```
title: Zigbee Network Chart
views:
  - theme: Backend-selected
    title: Home
    icon: mdi:zigbee
    panel: true
    type: panel
    subview: false
    path: default_view
    badges: []
    cards:
      - clickable: true
        panel: true
        columns:
          - name: Name
            prop: name
          - attr: available
            id: available
            modify: x || "false"
            name: Online
          - attr: manufacturer
            name: Manufacturer
          - attr: model
            name: Model
          - attr: ieee
            name: IEEE
          - name: NWK
            prop: nwk
          - attr: rssi
            name: RSSI
          - attr: lqi
            name: LQI
          - attr: last_seen
            name: Last Seen
          - attr: power_source
            name: Power Source
          - attr: quirk_class
            name: Quirk
        sort_by: available
        type: custom:zha-network-card
```
