### ISSUE TITLE
ZHA Network Card download issue

### ISSUE THREAD

**Issue by MondoXwan** [dmulcahey/zha-network-card#35]
ZHA Network Card

Custom Lovelace card that displays ZHA network and device information

This is a modified version of https://github.com/custom-cards/flex-table-card This implementation leverages the ZHA websocket API to get ZHA device information instead of using hass.states

After requesting download, this message shows up:

The version b6b05fa for this plugin can not be used with HACS.

**Comment by jeison-souza** [comment]
Same for me.

**Comment by 400HPMustang** [comment]
Follow the manual install instructions those worked for me.

**Comment by erkr** [comment]
![Image](https://github.com/user-attachments/assets/b36cf490-36b0-435b-8aa7-3fb0e8f756b6)

Of course we can install it manually. But this is the error described above

**Comment by cybertosher** [comment]
Will this ever be fixed? I am getting the same error and wondering if HACS will ever be a supported platform again?

**Comment by Orange-GT3** [comment]
Same error and even the manual install instructions are incorrect. Under resources, type should be module, not js.

The instructions also do not make it clear they are setting Lovelace to YAML mode which breaks all other Lovelace HACS items that have been downloaded.

Honestly, if this isn't going to be updated, it should be removed from HACS.

**Comment by erkr** [comment]
@Orange-GT3 it runs perfectly fine once copied manually into 'www/community/zha-network-card'
You just can't reinstall it via HACS

Setting 'Lovelace into yaml'??
The card doesn't support a visual editor. The yaml code entered in the card config is only for the editor and stored as JSON 

This is my config (and I don't run Lovelace in yaml mode, nothing gets broken either):
``` 
type: custom:zha-network-card
clickable: true
columns:
  - name: Name
    prop: name
  - attr: area_id
    name: area
  - attr: available
    id: available
    modify: x || "false"
    name: Online
  - attr: manufacturer
    name: Manufacturer
  - attr: model
    name: Model
  - attr: ieee
    name: IEEE
  - name: NWK
    prop: nwk
  - attr: rssi
    name: RSSI
  - attr: lqi
    name: LQI
  - attr: last_seen
    name: Last Seen
  - attr: power_source
    name: Power Source
  - attr: quirk_class
    name: Quirk
sort_by: available
```
